version: 2.1
workflows:
  Imagecreation:
    jobs:
     - build
     
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
        auth:
          username: Rakshit1806
          password: rakshit1806
    steps:
      - checkout
      - run: node --verison
    
